### ISSUE TITLE
[feature] Stats page

### ISSUE THREAD

**Issue by timoline** [nurikk/zigbee2mqtt-frontend#231]
A new stats page with stats like:

- Devices
- EndDevices
- Routers
- etc...

**Comment by nurikk** [comment]
Uh?

**Comment by timoline** [comment]
some stats...for example..

Devices 20
EndDevices 16
Routers 4
etc...

**Comment by nurikk** [comment]
Do these stats add any value for end users?

**Comment by timoline** [comment]
For some....Stats are always adding value...or doesn't it

**Comment by nurikk** [comment]
Find at least 20 of interesting in this and then let's discuss.
Happy new year 🥳

**Comment by timoline** [comment]
nope... let's do this and we will find more later
happy new year

**Comment by markheloking** [comment]
Am definitely interested in this.

**Comment by zen2** [comment]
I think it can be really interesting to have these stats when reporting zigbee2mqtt problems and most especially to show stability using differents coordinator and different zigbee mesh sizes.
So +1 including coordinator type and firmware.

**Comment by zen2** [comment]
Bump

**Comment by timoline** [comment]
why?

**Comment by svrooij** [comment]
> why?

Automatically if no response for some time.

**Comment by zen2** [comment]
Bump

**Comment by timoline** [comment]
bump

**Comment by zen2** [comment]
Statistics information about the zigbee network start to be as important as the network mesh grow up.
I got actually more than 90 devices. And it's a mess to check all devices one by one to see which model have optimistic option in used or not or to know which router a device is using....
So actually I use a bunch of bash scripts for that and I can't help properly zigbee2mqtt project when I need to open an issue and have to dig with my scripts to describe my network to help identify a bug.
If we could have a strong network statistics page we could even have an export button to export this data in order to add it in github issue report. That could avoid two pages of issue comment before realize that we all have the same kind of router device that bring the problem on different end devices.

**Comment by Bascht74** [comment]
I wish I would have that page. At least to see, if a device is unavailable and to see the connection (coordinator or specific router) would be a great help... 
I got 120 devices, hue and aqara

**Comment by nurikk** [comment]
done
